### ISSUE TITLE
Use  calls=normal_op

### ISSUE THREAD

**Issue by klahnakoski** [Generacion-tablas-SQL/TiposDatos_Generadores#1]
Good day!

Looking at  https://github.com/Generacion-tablas-SQL/TiposDatos_Generadores/blob/main/src/clasificador.py#L68  I see 

     operator = list(check.keys())[0].lower() 

which is unfortunate: Choosing the first key, hoping it the operation.  You can use `calls=normal_op` to help with your post processing:

    from mo_sql_parsing import parse, normal_op
    parse("select trim(' ' from b+c)", calls=normal_op)

which provides

```
{'select': {'value': {
    'op': 'trim', 
    'args': [{'op': 'add', 'args': ['b', 'c']}], 
    'kwargs': {'characters': {'literal': ' '}}
}}}
```

this is harder for humans to read, but it is easier to manipulate.  [more](https://github.com/klahnakoski/mo-sql-parsing#normalized-function-call-form-experimental)

Thank you for using mo-sql-parsing.  If you find it is missing any features (eg [limitations](https://github.com/Generacion-tablas-SQL/TiposDatos_Generadores/blob/main/docs/Limitations.md#limitaciones-del-proyecto)) please [add an issue](https://github.com/klahnakoski/mo-sql-parsing/issues/new), even if it just SQL fragment.

**Comment by LlucBonet** [comment]
Thank you for your help!
We've looked into it and we have changed the code.
