### ISSUE TITLE
Meter excepciones

### ISSUE THREAD

**Issue by LlucBonet** [Generacion-tablas-SQL/TiposDatos_Generadores#4]
Lanzar Exception cuando:
- [x] Restricciones insatisfactibles en una columna (por ejemplo:  col > 20 and col < 15)
- [x] Si generate_random() no consigue generar un dato que cumpla las restricciones

**Comment by AlvaroPlazaSanz** [comment]
Añadidas excepciones de momento en la clase origen (son recogidas todas en esta clase)
